### ISSUE TITLE
Webpack dev server example

### ISSUE THREAD

**Issue by danvoyce** [dotenv-org/examples#3]
Would it be possible to update this example so it also works with the dev server? 

When I pull it down and run `npm run dev` and open it up in the browser, all it returns is `Cannot GET /`

https://github.com/dotenv-org/examples/tree/master/dotenv-webpack

**Comment by motdotla** [comment]
That would be nice. I expected it to actually do that. Not sure why build and serve would function different here. I'll let someone with more webpack experience chime in. Closing for now.
