### ISSUE TITLE
examples/dotenv-nodejs README

### ISSUE THREAD

**Issue by eggsmayhem** [dotenv-org/examples#4]
For beginner friendliness, would it be possible to specify how to access the .env variables within the code, i.e. just a short line on using 
```
process.env.VARIABLE_NAME
```

**Comment by motdotla** [comment]
I'll leave that to the main repo to explain. I added a note on this README to point devs there: https://github.com/dotenv-org/examples/commit/1b26f07df66a829e5907bd31ce72b0015b2f776f
