### ISSUE TITLE
I got error ReferenceError: process is not defined

### ISSUE THREAD

**Issue by iWyse** [dotenv-org/examples#5]
i copy your code and got error ReferenceError: process is not defined.

Why ?

index.js 
import _ from 'lodash'

function component() {
  const elem = document.createElement('div')

  elem.innerHTML = _.join(['Hello', process.env.NAME], ' ')

  return elem
}

document.body.appendChild(component())

.env
NAME= CHANGE_ME

**Comment by meisammofidi** [comment]
Same as me :-(

**Comment by Awen-hub** [comment]
Me too.

**Comment by AleksRap** [comment]
Hi. You need to add a path to your file if the file is different from the default

Example: 
If your env file has name **.env.production** - you need to add in plugins next config: new Dotenv({ path: 'path to your file' })
